-- ============================================================
-- InnovaHack 2026 — Referral System Schema
-- ============================================================
-- Run this AFTER schema.sql in your Supabase SQL Editor.
-- This file adds the community partner referral tracking system.
-- ============================================================


-- ============================================================
-- TABLE: community_partners
-- Stores approved community partners and their unique ref codes
-- ============================================================
CREATE TABLE IF NOT EXISTS community_partners (
  id                    UUID DEFAULT uuid_generate_v4() PRIMARY KEY,

  -- Identity
  community_name        TEXT NOT NULL,
  community_platform    TEXT,
  community_website     TEXT,
  community_size        TEXT,
  community_focus       TEXT,

  -- Contact
  contact_person_name   TEXT NOT NULL,
  email                 TEXT NOT NULL,
  phone_number          TEXT,
  role_in_community     TEXT,

  -- Referral
  ref_code              TEXT NOT NULL UNIQUE,
  -- ref_code is the unique slug used in ?ref=<code>
  -- e.g. "gdg-mumbai", "devs-pune", "ieee-vit"
  -- generated by admin or auto-derived from community_name

  referral_link         TEXT GENERATED ALWAYS AS (
    'https://innovahack.in/register?ref=' || ref_code
  ) STORED,
  -- NOTE: update the base URL above to match your production domain

  -- Stats (denormalised cache — updated by trigger)
  total_referrals       INTEGER DEFAULT 0,
  -- incremented whenever a registration is inserted with this ref_code

  -- Proposal linkage (optional — links back to partner_proposals row)
  proposal_id           UUID REFERENCES partner_proposals(id) ON DELETE SET NULL,

  -- Status
  status                TEXT DEFAULT 'pending'
                        CHECK (status IN ('pending', 'approved', 'suspended', 'rejected')),
  -- pending  = proposal received, not yet reviewed
  -- approved = ref code is live and tracking
  -- suspended = temporarily paused
  -- rejected  = not accepted

  -- Tier reward tracking
  reward_tier           TEXT CHECK (reward_tier IN ('gold', 'silver', 'bronze', NULL)),
  -- populated by admin once the hackathon concludes

  -- Admin notes
  notes                 TEXT,

  -- Timestamps
  created_at            TIMESTAMPTZ DEFAULT NOW(),
  updated_at            TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_community_partners_ref_code  ON community_partners (ref_code);
CREATE INDEX IF NOT EXISTS idx_community_partners_status    ON community_partners (status);
CREATE INDEX IF NOT EXISTS idx_community_partners_referrals ON community_partners (total_referrals DESC);


-- ============================================================
-- ADD ref_code COLUMN TO registrations
-- Tracks which community partner referred this applicant
-- ============================================================
ALTER TABLE registrations
  ADD COLUMN IF NOT EXISTS ref_code TEXT REFERENCES community_partners(ref_code)
    ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE registrations
  ADD COLUMN IF NOT EXISTS referral_source TEXT;
  -- stores the raw ?ref= value even if it doesn't match a known code
  -- useful for auditing typos / fake codes

CREATE INDEX IF NOT EXISTS idx_registrations_ref_code ON registrations (ref_code);


-- ============================================================
-- FUNCTION: increment total_referrals on community_partners
-- Triggered whenever a new registration with a valid ref_code is inserted
-- ============================================================
CREATE OR REPLACE FUNCTION increment_referral_count()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.ref_code IS NOT NULL THEN
    UPDATE community_partners
    SET
      total_referrals = total_referrals + 1,
      updated_at      = NOW()
    WHERE ref_code = NEW.ref_code;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_increment_referral_count
  AFTER INSERT ON registrations
  FOR EACH ROW
  EXECUTE FUNCTION increment_referral_count();


-- ============================================================
-- FUNCTION: decrement total_referrals when a registration is deleted
-- ============================================================
CREATE OR REPLACE FUNCTION decrement_referral_count()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.ref_code IS NOT NULL THEN
    UPDATE community_partners
    SET
      total_referrals = GREATEST(total_referrals - 1, 0),
      updated_at      = NOW()
    WHERE ref_code = OLD.ref_code;
  END IF;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_decrement_referral_count
  AFTER DELETE ON registrations
  FOR EACH ROW
  EXECUTE FUNCTION decrement_referral_count();


-- ============================================================
-- FUNCTION: handle ref_code change on registration update
-- If a registration's ref_code is changed, adjust both counters
-- ============================================================
CREATE OR REPLACE FUNCTION handle_referral_count_on_update()
RETURNS TRIGGER AS $$
BEGIN
  -- Old ref_code loses a referral
  IF OLD.ref_code IS NOT NULL AND OLD.ref_code IS DISTINCT FROM NEW.ref_code THEN
    UPDATE community_partners
    SET
      total_referrals = GREATEST(total_referrals - 1, 0),
      updated_at      = NOW()
    WHERE ref_code = OLD.ref_code;
  END IF;

  -- New ref_code gains a referral
  IF NEW.ref_code IS NOT NULL AND NEW.ref_code IS DISTINCT FROM OLD.ref_code THEN
    UPDATE community_partners
    SET
      total_referrals = total_referrals + 1,
      updated_at      = NOW()
    WHERE ref_code = NEW.ref_code;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_handle_referral_count_on_update
  AFTER UPDATE OF ref_code ON registrations
  FOR EACH ROW
  EXECUTE FUNCTION handle_referral_count_on_update();


-- ============================================================
-- FUNCTION: auto-generate ref_code from community_name
-- Call this when creating a community partner without a manual code
-- Usage: SELECT generate_ref_code('GDG Mumbai');  --> 'gdg-mumbai'
-- ============================================================
CREATE OR REPLACE FUNCTION generate_ref_code(p_community_name TEXT)
RETURNS TEXT AS $$
DECLARE
  v_base  TEXT;
  v_code  TEXT;
  v_count INTEGER := 0;
BEGIN
  -- Lowercase, replace spaces/special chars with hyphens, strip doubles
  v_base := LOWER(
    REGEXP_REPLACE(
      REGEXP_REPLACE(p_community_name, '[^a-zA-Z0-9\s-]', '', 'g'),
      '\s+', '-', 'g'
    )
  );
  -- Trim leading/trailing hyphens
  v_base := TRIM(BOTH '-' FROM v_base);
  -- Truncate to 32 chars
  v_base := SUBSTRING(v_base, 1, 32);

  v_code := v_base;

  -- Ensure uniqueness by appending a counter if needed
  WHILE EXISTS (SELECT 1 FROM community_partners WHERE ref_code = v_code) LOOP
    v_count := v_count + 1;
    v_code  := v_base || '-' || v_count;
  END LOOP;

  RETURN v_code;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- FUNCTION: approve community partner proposal and create partner record
-- Automatically generates a ref_code and creates the community_partners row
-- when a partner_proposals row of type community_partner is approved.
-- Usage: SELECT approve_community_partner('<proposal_uuid>');
-- ============================================================
CREATE OR REPLACE FUNCTION approve_community_partner(p_proposal_id UUID)
RETURNS community_partners AS $$
DECLARE
  v_proposal  partner_proposals%ROWTYPE;
  v_ref_code  TEXT;
  v_partner   community_partners%ROWTYPE;
BEGIN
  -- Fetch the proposal
  SELECT * INTO v_proposal
  FROM partner_proposals
  WHERE id = p_proposal_id
    AND proposal_type = 'community_partner';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'No community_partner proposal found with id = %', p_proposal_id;
  END IF;

  -- Generate a unique ref_code
  v_ref_code := generate_ref_code(COALESCE(v_proposal.community_name, 'community'));

  -- Insert the community partner record
  INSERT INTO community_partners (
    community_name,
    community_platform,
    community_website,
    community_size,
    community_focus,
    contact_person_name,
    email,
    phone_number,
    role_in_community,
    ref_code,
    proposal_id,
    status
  ) VALUES (
    v_proposal.community_name,
    v_proposal.community_platform,
    v_proposal.community_website_link,
    v_proposal.community_size,
    v_proposal.community_focus,
    v_proposal.contact_person_name,
    v_proposal.email,
    v_proposal.phone_number,
    (v_proposal.additional_message),   -- role_in_community stored here by the form
    v_ref_code,
    p_proposal_id,
    'approved'
  )
  RETURNING * INTO v_partner;

  -- Mark the proposal as converted
  UPDATE partner_proposals
  SET status = 'converted', updated_at = NOW()
  WHERE id = p_proposal_id;

  RETURN v_partner;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- VIEW: referral_leaderboard
-- Live-computed leaderboard ranked by total_referrals DESC
-- ============================================================
CREATE OR REPLACE VIEW referral_leaderboard AS
SELECT
  cp.id,
  cp.ref_code,
  cp.referral_link,
  cp.community_name,
  cp.community_platform,
  cp.community_size,
  cp.contact_person_name,
  cp.email,
  cp.status,
  cp.reward_tier,
  cp.total_referrals,

  -- Live count directly from registrations (source of truth)
  COUNT(r.id)                                        AS live_referral_count,

  -- Breakdown by registration status
  COUNT(r.id) FILTER (WHERE r.status = 'pending')    AS pending_count,
  COUNT(r.id) FILTER (WHERE r.status = 'shortlisted') AS shortlisted_count,
  COUNT(r.id) FILTER (WHERE r.status = 'confirmed')  AS confirmed_count,
  COUNT(r.id) FILTER (WHERE r.status = 'rejected')   AS rejected_count,

  -- Rank within approved partners
  RANK() OVER (
    PARTITION BY cp.status
    ORDER BY COUNT(r.id) DESC
  ) AS rank_position,

  cp.created_at,
  cp.updated_at

FROM community_partners cp
LEFT JOIN registrations r ON r.ref_code = cp.ref_code
GROUP BY cp.id
ORDER BY live_referral_count DESC;


-- ============================================================
-- VIEW: referral_registrations
-- All registrations that came through a referral link
-- ============================================================
CREATE OR REPLACE VIEW referral_registrations AS
SELECT
  r.id              AS registration_id,
  r.full_name,
  r.email           AS registrant_email,
  r.contact_no,
  r.city,
  r.team_type,
  r.status          AS registration_status,
  r.created_at      AS registered_at,
  r.ref_code,
  r.referral_source,
  cp.community_name,
  cp.contact_person_name AS community_contact,
  cp.email          AS community_email,
  cp.community_platform
FROM registrations r
LEFT JOIN community_partners cp ON cp.ref_code = r.ref_code
WHERE r.ref_code IS NOT NULL
   OR r.referral_source IS NOT NULL
ORDER BY r.created_at DESC;


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================
ALTER TABLE community_partners ENABLE ROW LEVEL SECURITY;

-- Public can read approved partners (needed to validate ref codes on registration)
CREATE POLICY "community_partners_public_read_approved"
  ON community_partners FOR SELECT
  USING (status = 'approved');

-- Authenticated admins have full access
CREATE POLICY "community_partners_admin_all"
  ON community_partners FOR ALL
  USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- Views inherit the underlying table policies
-- Grant SELECT on views to anon and authenticated roles
GRANT SELECT ON referral_leaderboard    TO anon, authenticated;
GRANT SELECT ON referral_registrations  TO authenticated;


-- ============================================================
-- AUTO-UPDATE updated_at trigger for community_partners
-- ============================================================
CREATE TRIGGER trigger_community_partners_updated_at
  BEFORE UPDATE ON community_partners
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- ============================================================
-- RESYNC FUNCTION: rebuild total_referrals from scratch
-- Run this if the cached counts ever drift from live data:
--   SELECT resync_referral_counts();
-- ============================================================
CREATE OR REPLACE FUNCTION resync_referral_counts()
RETURNS void AS $$
BEGIN
  UPDATE community_partners cp
  SET
    total_referrals = (
      SELECT COUNT(*) FROM registrations r WHERE r.ref_code = cp.ref_code
    ),
    updated_at = NOW();
END;
$$ LANGUAGE plpgsql;
